services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app_network

    web:
      image: nginx:alpine
      container_name: url-shortener-web
      restart: unless-stopped
      ports:
        - "8000:80"
      volumes:
        - .:/var/www
        - ./default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - app_network

  db:
    image: postgres:15
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    restart: unless-stopped
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
